/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ad.vistas;

import com.ad.ad06.Main;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * PanelPrincipal
 */
public class PanelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        butonVerMensaxes = new javax.swing.JButton();
        butonVerMensaxesUsuarios = new javax.swing.JButton();
        butonBuscarHashTag = new javax.swing.JButton();
        butonEscribirMensaxe = new javax.swing.JButton();
        butonBuscarUsuario = new javax.swing.JButton();
        butonSair = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butonVerMensaxes.setText("Ver tódalas mensaxes");
        butonVerMensaxes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonVerMensaxesMouseClicked(evt);
            }
        });

        butonVerMensaxesUsuarios.setText("Ver mensaxes de usuarios que sigo");
        butonVerMensaxesUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonVerMensaxesUsuariosMouseClicked(evt);
            }
        });

        butonBuscarHashTag.setText("Buscar por hashtag");
        butonBuscarHashTag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonBuscarHashTagMouseClicked(evt);
            }
        });

        butonEscribirMensaxe.setText("Escribir unha mensaxe");
        butonEscribirMensaxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonEscribirMensaxeMouseClicked(evt);
            }
        });

        butonBuscarUsuario.setText("Buscar Usuario");
        butonBuscarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonBuscarUsuarioMouseClicked(evt);
            }
        });

        butonSair.setText("Sair");
        butonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butonVerMensaxes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonVerMensaxesUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(butonBuscarHashTag, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(butonEscribirMensaxe, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(butonBuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(butonVerMensaxes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butonVerMensaxesUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butonBuscarHashTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butonEscribirMensaxe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butonBuscarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(butonSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonSairMouseClicked
        
        Main.framePanelPrincipal.setVisible(false);
        Main.frameInicio.setVisible(true);
        Main.nomeUsuario = StringUtils.EMPTY;
        
    }//GEN-LAST:event_butonSairMouseClicked

    private void butonBuscarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonBuscarUsuarioMouseClicked
        
        Main.framePanelPrincipal.setVisible(false);
        Main.frameBuscarUsuarios.setVisible(true);
        
    }//GEN-LAST:event_butonBuscarUsuarioMouseClicked

    private void butonEscribirMensaxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonEscribirMensaxeMouseClicked
        
        Main.framePanelPrincipal.setVisible(false);
        Main.frameCrearMensajes.setVisible(true);
        
    }//GEN-LAST:event_butonEscribirMensaxeMouseClicked

    private void butonVerMensaxesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonVerMensaxesMouseClicked
        
        Main.framePanelPrincipal.setVisible(false);
        Main.frameVerMensaxes.setVisible(true);
        
        //Asociar operacion
        Main.frameVerMensaxes.verTodosMensaxes = Boolean.TRUE;
        
    }//GEN-LAST:event_butonVerMensaxesMouseClicked

    private void butonVerMensaxesUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonVerMensaxesUsuariosMouseClicked
        
        Main.framePanelPrincipal.setVisible(false);
        Main.frameVerMensaxes.setVisible(true);
        
        //Asociar operacion
        Main.frameVerMensaxes.verTodosMensaxes = Boolean.FALSE;
        
    }//GEN-LAST:event_butonVerMensaxesUsuariosMouseClicked

    private void butonBuscarHashTagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonBuscarHashTagMouseClicked
        
        Main.framePanelPrincipal.setVisible(false);
        Main.frameVerMensaxes.setVisible(true);
        
        //Asociar operacion
        Main.frameVerMensaxes.verTodosMensaxes = Boolean.TRUE;
        
    }//GEN-LAST:event_butonBuscarHashTagMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonBuscarHashTag;
    private javax.swing.JButton butonBuscarUsuario;
    private javax.swing.JButton butonEscribirMensaxe;
    private javax.swing.JButton butonSair;
    private javax.swing.JButton butonVerMensaxes;
    private javax.swing.JButton butonVerMensaxesUsuarios;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
