/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ad.vistas;

import com.ad.ad06.Main;
import com.ad.exception.ADException;
import com.ad.mongoDB.MensaxesUtiles;
import com.ad.mongoDB.vo.Mensaxe;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author manureyesi
 */
public class VerMensaxes extends javax.swing.JFrame {

    public Boolean verTodosMensaxes;
    
    private DefaultTableModel modelo;
    
    /**
     * Creates new form VerMensaxes
     */
    public VerMensaxes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMensaxes = new javax.swing.JTable();
        botonBuscar = new javax.swing.JButton();
        textoBuscar = new javax.swing.JTextField();
        textoError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        butonSair.setText("Sair");
        butonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonSairMouseClicked(evt);
            }
        });

        tablaMensaxes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMensaxes.setEnabled(false);
        jScrollPane2.setViewportView(tablaMensaxes);

        botonBuscar.setText("Buscar");
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textoError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar)
                    .addComponent(textoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoError, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(butonSair))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonSairMouseClicked
        
        Main.framePanelPrincipal.setVisible(true);
        Main.frameVerMensaxes.setVisible(false);
        this.textoBuscar.setText(StringUtils.EMPTY);
        
    }//GEN-LAST:event_butonSairMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        this.textoBuscar.setText(StringUtils.EMPTY);
        String cabecera[]={"Nome", "Username", "Mensaxe", "Data"};
        String datos[][]={};
        this.modelo = new DefaultTableModel(datos, cabecera);
        this.tablaMensaxes.setModel(this.modelo);
        
        try {
        
            List<Mensaxe> listaMensaxes = null;
            
            if (this.verTodosMensaxes) {
                //Buscar mensaxes
                listaMensaxes = MensaxesUtiles.buscarMensaxes();
            } else {
                //solo mensaxes de seguidores
                listaMensaxes = MensaxesUtiles.buscarMensaxesSeguidos();
            }
                    
            
            for (Mensaxe men: listaMensaxes) {
                Object datosMen[]={men.getNome(), men.getUsername(), men.getTexto(), men.getDate()};
                modelo.addRow(datosMen);
            }
            
        } catch (ADException e) {
            this.textoError.setText(e.getDescripcionError());
        } 
        
    }//GEN-LAST:event_formWindowActivated

    private void botonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseClicked
        
        if (StringUtils.isNotBlank(this.textoBuscar.getText())) {
        
            String cabecera[]={"Nome", "Username", "Mensaxe", "Data"};
            String datos[][]={};
            this.modelo = new DefaultTableModel(datos, cabecera);
            this.tablaMensaxes.setModel(this.modelo);
            
            try {
                
                for (Mensaxe men: MensaxesUtiles.buscarFiltroMensaxes(this.textoBuscar.getText())) {
                    Object datosMen[]={men.getNome(), men.getUsername(), men.getTexto(), men.getDate()};
                    modelo.addRow(datosMen);
                }
                
            } catch (ADException e) {
                this.textoError.setText(e.getDescripcionError());
            }
            
        } else {
            this.textoError.setText("No se permiten campos vacios.");
        }
        
    }//GEN-LAST:event_botonBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerMensaxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerMensaxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerMensaxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerMensaxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerMensaxes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton butonSair;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaMensaxes;
    private javax.swing.JTextField textoBuscar;
    private javax.swing.JLabel textoError;
    // End of variables declaration//GEN-END:variables
}
